export const events = [
  {
    id: 1,
    title: 'Dream World Wide in Jakarta',
    location: 'Asdasdasf gfgrh weffasdas dasdasfegfs',
    venue: 'Lasndl ldsknandsadmn slndla',
    price: 10.0,
    date: '18 Sep',
    isFavourite: false,
  },
  {
    id: 2,
    title: 'Dream World Wide in Jakarta',
    location: 'Asdasdasf gfgrh weffasdas dasdasfegfs',
    venue: 'Lasndl ldsknandsadmn slndla',
    price: 10.0,
    date: '18 Sep',
    isFavourite: true,
  },
  {
    id: 3,
    title: 'Dream World Wide in Jakarta',
    location: 'Asdasdasf gfgrh weffasdas dasdasfegfs',
    venue: 'Lasndl ldsknand',
    price: 10.0,
    date: '18 Sep',
    isFavourite: false,
  },
  {
    id: 4,
    title: 'Dream World Wide in Jakarta',
    location: 'Asdasdasf gfgrh weffasdas dasdasfegfs',
    venue: 'Lasndl ldsknandsadmn slndla',
    price: 10.0,
    date: '18 Sep',
    isFavourite: true,
  },
  {
    id: 5,
    title: 'Dream World Wide in Jakarta',
    location: 'Asdasdasf gfgrh weffasdas dasdasfegfs',
    venue: 'Lasndl ldsknandsadmn slndla',
    price: 10.0,
    date: '18 Sep',
    isFavourite: false,
  },
  {
    id: 6,
    title: 'Dream World Wide in Jakarta',
    location: 'Asdasdasf gfgrh weffasdas dasdasfegfs',
    venue: 'Lasndl ldsknandsadmn slndla',
    price: 10.0,
    date: '18 Sep',
    isFavourite: true,
  },
];
