export const events = [
  {
    id: 1,
    title: 'Dream World Wide in Jakarta',
    location: 'Braga, Portugal',
    price: 10.0,
    date: '18 September 2023',
    isFavourite: false,
  },
  {
    id: 2,
    title: 'Dream World Wide in Jakarta',
    location: 'Braga, Portugal',
    price: 10.0,
    date: '18 September 2023',
    isFavourite: true,
  },
  {
    id: 3,
    title: 'Dream World Wide in Jakarta',
    location: 'Braga, Portugal',
    price: 10.0,
    date: '18 September 2023',
    isFavourite: false,
  },
  {
    id: 4,
    title: 'Dream World Wide in Jakarta',
    location: 'Braga, Portugal',
    price: 10.0,
    date: '18 September 2023',
    isFavourite: true,
  },
  {
    id: 5,
    title: 'Dream World Wide in Jakarta',
    location: 'Braga, Portugal',
    price: 10.0,
    date: '18 September 2023',
    isFavourite: false,
  },
  {
    id: 6,
    title: 'Dream World Wide in Jakarta',
    location: 'Braga, Portugal',
    price: 10.0,
    date: '18 September 2023',
    isFavourite: true,
  },
  {
    id: 7,
    title: 'Dream World Wide in Jakarta',
    location: 'Braga, Portugal',
    price: 10.0,
    date: '18 September 2023',
    isFavourite: false,
  },
  {
    id: 8,
    title: 'Dream World Wide in Jakarta',
    location: 'Braga, Portugal',
    price: 10.0,
    date: '18 September 2023',
    isFavourite: true,
  },
];
